#!/bin/bash

# Test script for selection preservation in Marco markdown editor

echo "🧪 Marco Selection Preservation Test - ENHANCED VERSION"
echo "======================================================"
echo ""
echo "RECENT FIXES APPLIED:"
echo "• Enhanced debug logging in formatting functions"
echo "• Improved focus management with timeout mechanisms"
echo "• Prevented toolbar buttons from stealing focus (set_can_focus(false))"
echo "• Added robust selection restoration logic"
echo ""
echo "Instructions for manual testing:"
echo ""
echo "1. Run the Marco application:"
echo "   cargo run"
echo ""
echo "2. Type some test text in the editor, for example:"
echo "   'This is some test text for formatting'"
echo ""
echo "3. Select the word 'test' with your mouse"
echo ""
echo "4. Click the Bold (𝐁) button in the toolbar"
echo "   - Text should become '**test**'"
echo "   - The text '**test**' should remain selected"
echo "   - Check terminal for debug output"
echo ""
echo "5. With '**test**' still selected, click Bold (𝐁) again"
echo "   - Text should become 'test' (formatting removed)"
echo "   - The text 'test' should remain selected"
echo "   - Check terminal for debug output"
echo ""
echo "6. With 'test' still selected, click Italic (𝐼)"
echo "   - Text should become '*test*'"
echo "   - The text '*test*' should remain selected"
echo ""
echo "7. Test the same with menu actions (Insert > Bold, etc.)"
echo ""
echo "8. Test the same with context menu (right-click)"
echo ""
echo "9. Test rapid consecutive clicks (Bold -> Italic -> Bold -> Italic)"
echo ""
echo "EXPECTED DEBUG OUTPUT:"
echo "• 'DEBUG: Selection exists before formatting'"
echo "• 'DEBUG: toggle_format_selection_only called with prefix=...'"
echo "• 'DEBUG: Selection set after applying/removing formatting'"
echo "• 'DEBUG: Selection preserved after formatting'"
echo "• 'DEBUG: Selection maintained after timeout'"
echo ""
echo "✅ SUCCESS: If selection is preserved after each action"
echo "❌ FAILURE: If selection is lost and you get error dialogs"
echo ""
echo "If the issue persists, the debug output will help identify whether"
echo "the problem is in the formatting logic itself or in focus handling."
echo ""
echo "Running application now..."
echo ""

# Run the application
cd "$(dirname "$0")"
cargo run
