#!/bin/bash

# Selection Preservation Test Script
# This script provides step-by-step testing instructions for the selection preservation feature

echo "=== Marco Selection Preservation Test ==="
echo ""
echo "This script will guide you through testing the selection preservation functionality."
echo "Make sure Marco is running with a test document open."
echo ""

echo "📝 Test 1: Basic Bold Formatting"
echo "1. Select the word 'test' in the editor"
echo "2. Click the Bold (𝐁) toolbar button" 
echo "3. Verify: The text becomes '**test**' and remains selected"
echo "4. Click Bold button again"
echo "5. Verify: The text becomes 'test' and remains selected"
echo "6. Expected debug output: 'Selection preserved successfully'"
echo ""
read -p "Press Enter when Test 1 is complete..."

echo "📝 Test 2: Multiple Formatting"
echo "1. Select plain text"
echo "2. Apply Bold formatting (should remain selected)"
echo "3. Apply Italic formatting (should become '***text***' and remain selected)"
echo "4. Apply Bold again (should become '*text*' and remain selected)"
echo "5. Apply Italic again (should become 'text' and remain selected)"
echo ""
read -p "Press Enter when Test 2 is complete..."

echo "📝 Test 3: Smart Expansion"
echo "1. Type: **example** (with bold formatting)"
echo "2. Select just 'example' (the inner text, not the asterisks)"
echo "3. Click Bold button"
echo "4. Verify: The entire '**example**' is detected and removed to become 'example'"
echo "5. Text should remain selected"
echo ""
read -p "Press Enter when Test 3 is complete..."

echo "📝 Test 4: Rapid Clicking"
echo "1. Select some text"
echo "2. Rapidly click Bold button multiple times (3-4 clicks quickly)"
echo "3. Verify: No error dialogs appear"
echo "4. Text toggles between formatted and unformatted"
echo "5. Selection is maintained throughout"
echo ""
read -p "Press Enter when Test 4 is complete..."

echo "📝 Test 5: Menu and Context Menu"
echo "1. Select text"
echo "2. Use Insert → Bold from main menu"
echo "3. Verify: Selection preserved"
echo "4. Right-click selected text"
echo "5. Use Bold from context menu"
echo "6. Verify: Selection preserved"
echo ""
read -p "Press Enter when Test 5 is complete..."

echo "📝 Test 6: Other Formatting Types"
echo "1. Test Italic (𝐼) button with selection preservation"
echo "2. Test Inline Code (</>) button with selection preservation"
echo "3. Test Strikethrough (𝕊) button with selection preservation"
echo "4. Verify each maintains selection after formatting"
echo ""
read -p "Press Enter when Test 6 is complete..."

echo "✅ Testing Complete!"
echo ""
echo "Expected behavior:"
echo "- All formatting operations should preserve text selection"
echo "- No 'Text Selection Required' error dialogs for consecutive operations"
echo "- Debug output should show 'Selection preserved successfully'"
echo "- Smart expansion should work for inner text selection"
echo ""
echo "If any test failed, check the console output for debug messages."
echo "Look for patterns like 'Selection lost after...' to identify timing issues."
echo ""
echo "Common issues and solutions:"
echo "- If selection is lost immediately: Check button focus settings"
echo "- If selection is lost after delay: Timing issue with GTK events"
echo "- If smart expansion fails: Check text parsing logic"
echo "- If rapid clicking fails: Adjust recent action timeout"
