/// The html_viewer.rs is a UI component that displays the HTML output generated by the backend renderer in html.rs. 
/// It does not perform the actual Markdown-to-HTML conversion itself; instead,
/// it takes the already-rendered HTML and presents it in the UI.

use gtk4::prelude::*;
use webkit6::prelude::*;

use webkit6::WebView;

/// Create a WebView widget and load the provided HTML string.
/// This replaces the previous AST rendering logic.
pub fn create_html_viewer(html: &str) -> WebView {
    let webview = WebView::new();
    webview.load_html(html, None);
    webview.set_vexpand(true);
    webview.set_hexpand(true);
    webview
}

pub fn wrap_html_document(body: &str) -> String {
    format!(
        r#"<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <style>body {{ font-family: sans-serif; }}</style>
  </head>
  <body>{}</body>
</html>"#,
        body
    )
}
