//! RTL (Right-to-Left) / LTR text direction management for the Marco application.
//!
//! GTK4 uses two mechanisms to control widget layout direction:
//!
//! 1. `gtk4::Widget::set_default_direction(dir)` — application-wide default used by
//!    every widget whose direction is `TextDirection::None` (the factory default).
//!    Must be called before OR after widgets are created; GTK re-evaluates the
//!    effective direction whenever it is queried.
//!
//! 2. `Widget::set_direction(dir)` called on an individual widget — overrides the
//!    global default for that widget and propagates to its children that still carry
//!    `TextDirection::None`.
//!
//! Strategy used here: set both the global default **and** the root window direction.
//! Setting the window direction cascades to every child widget that has not been
//! given an explicit non-`None` direction — which covers toolbars, menus, popovers,
//! TOC panel, footer, split view, and the editor itself.  The source view is also
//! set explicitly in case it was previously given a cached explicit direction by an
//! earlier toggle.
//!
//! The HTML preview direction is handled separately: `is_rtl_global()` is read by
//! `backend::wrap_html_document` to inject `dir="rtl"` / `dir="ltr"` into every
//! generated `<html>` element, and a JS call updates the live preview instantly.
//!
//! Reference: <https://docs.gtk.org/gtk4/method.Widget.set_direction.html>
//!            <https://docs.gtk.org/gtk4/type_func.Widget.set_default_direction.html>

use gtk4::prelude::*;
use gtk4::{ApplicationWindow, TextDirection};
use sourceview5::prelude::*;
use sourceview5::{GutterRendererText, View as SourceView};
use std::cell::RefCell;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

use marco_shared::logic::swanson::SettingsManager;

// ─── Global RTL state ───────────────────────────────────────────────────────

/// Tracks the current RTL state at runtime.
/// Set early (before preview HTML is generated) via `init_rtl_from_settings`,
/// and kept in sync on every toggle via `apply_text_direction`.
static RTL_ACTIVE: AtomicBool = AtomicBool::new(false);

/// Whether line numbers were visible on the left gutter before RTL was activated.
/// Used to restore them when switching back to LTR.
static RTL_SAVED_LINE_NUMBERS: AtomicBool = AtomicBool::new(false);

thread_local! {
    /// Custom `GutterRendererText` inserted into the right gutter in RTL mode
    /// to show line numbers on the correct (logical-end) side.
    /// Created lazily on the first RTL activation and reused on subsequent toggles.
    static RTL_LINE_RENDERER: RefCell<Option<GutterRendererText>> = const { RefCell::new(None) };
}

/// Returns `true` when RTL layout is currently active.
/// Read by `backend::wrap_html_document` to inject the correct `dir` attribute.
pub fn is_rtl_global() -> bool {
    RTL_ACTIVE.load(Ordering::Relaxed)
}

fn set_rtl_global(rtl: bool) {
    RTL_ACTIVE.store(rtl, Ordering::Relaxed);
}

/// Sets the right-gutter renderer's minimum width to fit `line_count` digits.
///
/// Measures the pixel width of a string of the same digit-count as `line_count`
/// using the renderer's own font, then calls `set_size_request` so GTK allocates
/// enough space.  Returns early when the renderer is not yet realized (measure → 0).
fn set_renderer_size_for_line_count(renderer: &GutterRendererText, line_count: i32) {
    // Count the number of decimal digits needed.
    let mut n = line_count.max(1) as u32;
    let mut digits = 0usize;
    while n > 0 {
        n /= 10;
        digits += 1;
    }
    // Build a template string of the worst-case width ("9" is widest in most fonts).
    // Always reserve at least two digits so single-digit files look consistent.
    let template: String = "9".repeat(digits.max(2));
    let (w, _) = sourceview5::prelude::GutterRendererTextExt::measure(renderer, &template);
    if w > 0 {
        // Add 2 × xpad (12 px each side = 24 total) to match the built-in renderer's spacing.
        renderer.set_size_request(w + 24, -1);
    }
}

// ─── Public helpers ─────────────────────────────────────────────────────────

/// Returns `true` when the persisted `layout.text_direction` setting is `"rtl"`.
pub fn is_rtl_from_settings(settings_manager: &Arc<SettingsManager>) -> bool {
    settings_manager
        .get_settings()
        .layout
        .as_ref()
        .and_then(|l| l.text_direction.as_deref())
        .map(|dir| dir.eq_ignore_ascii_case("rtl"))
        .unwrap_or(false)
}

/// Reads the persisted direction from settings and sets the global RTL flag.
///
/// Call this **before** `create_editor_with_preview_and_buffer` so that any
/// initial HTML generated by `wrap_html_document` already embeds the correct
/// `dir` attribute.  (The GTK widget directions are applied later via
/// `apply_text_direction` once the window and editor view exist.)
pub fn init_rtl_from_settings(settings_manager: &Arc<SettingsManager>) {
    set_rtl_global(is_rtl_from_settings(settings_manager));
}

/// Applies the requested text direction to the **entire** Marco application.
///
/// Calling this function:
///
/// * Updates the global RTL flag so subsequent calls to `wrap_html_document`
///   embed the correct `dir` attribute.
///
/// * Sets the direction on the root `window` and on `editor_view` / its parent
///   `ScrolledWindow` **before** updating the application-wide default.
///   Order matters: `gtk4::Widget::set_default_direction` walks the entire
///   widget tree and fires `direction-changed` only on widgets whose stored
///   direction is `TextDirection::None`.  If it ran first, every widget's
///   *effective* direction would already equal `dir`, so the subsequent
///   per-widget calls would see old = new and emit nothing — leaving the
///   editor's Pango layout direction unchanged.  By setting explicit directions
///   first (while the global default still reflects the previous value), GTK
///   detects the change and fires `direction-changed`, which updates the Pango
///   layout and queues a redraw.
///
/// * Updates the GTK application-wide default last so that newly created
///   widgets (dialogs, tooltips, popovers) also pick up the correct direction.
///
/// **Note on gutter position**: `GtkTextView::size_allocate` always places the
/// left gutter widget at physical x = 0 and the right gutter after the text
/// area, with no direction-aware swapping.  As a result, the line-number gutter
/// remains at the physical left edge even in RTL mode.  The Pango text layout
/// and cursor position do flip correctly; only the gutter's screen-side is a
/// known GTK4 limitation.
///
/// The combined effect flips the entire UI: menus migrate to the correct side,
/// the toolbar and footer mirror their content, the split view reverses panel
/// order, the scrollbar moves to the start edge, and the text editor renders
/// content in the new direction with text aligned to the correct edge.
///
/// **Note on `set_direction` vs `set_justification`**: these are two orthogonal
/// properties.  `set_direction(RTL)` updates the Pango bidi base direction and
/// moves the cursor to the right on empty lines — but leaves LTR (ASCII/Latin)
/// text visually left-aligned because `GTK_JUSTIFY_LEFT` is screen-absolute.
/// `set_justification(Right)` is what makes text visually align to the right
/// edge in RTL mode.  Both are applied here so that both behaviour groups work.
pub fn apply_text_direction(rtl: bool, window: &ApplicationWindow, editor_view: &SourceView) {
    // Capture *previous* state before mutating the global flag so every
    // guard below can distinguish a real direction change from a no-op call.
    let previously_rtl = is_rtl_global();

    // Keep global in sync — must happen before any wrap_html_document call.
    set_rtl_global(rtl);

    let dir = if rtl {
        TextDirection::Rtl
    } else {
        TextDirection::Ltr
    };

    // Justification: set_direction(RTL) alone has no visible effect on LTR/ASCII
    // text because GTK_JUSTIFY_LEFT is absolute screen-left, not logical start.
    // set_justification(Right) makes text visually align to the right edge in RTL
    // mode, which is the observable change the user expects.  The two properties
    // are orthogonal: direction controls bidi/cursor behaviour; justification
    // controls alignment.
    let justification = if rtl {
        gtk4::Justification::Right
    } else {
        gtk4::Justification::Left
    };

    // Step 1 — set explicit directions and justification on key widgets FIRST.
    // The global default still equals the previous direction here, so GTK will
    // detect old_effective != new and emit the direction-changed signal on each
    // widget, which cascades through layout invalidation and queue_draw.
    window.set_direction(dir);
    editor_view.set_direction(dir);
    editor_view.set_justification(justification);

    // ── Gutter: move line numbers to the logical-end side ──────────────────
    // GTK4 gutters are positioned by physical side (LEFT always at x=0, RIGHT
    // at x=text_end).  In RTL mode we move line numbers from the left gutter to
    // the right gutter so they appear beside the "start" of RTL text.
    // GtkSourceGutterRendererLines is private; we use GutterRendererText with a
    // query_data callback that formats the 1-based line number.
    if rtl {
        // Need to set up the gutter from scratch when either:
        // (a) this is a live LTR→RTL toggle, OR
        // (b) the renderer doesn't exist yet (startup in RTL: init_rtl_from_settings
        //     pre-set RTL_ACTIVE=true for HTML generation, so previously_rtl==true even
        //     though the gutter has never been configured).
        let renderer_is_new = RTL_LINE_RENDERER.with(|c| c.borrow().is_none());
        if !previously_rtl || renderer_is_new {
            // LTR→RTL transition (or first startup in RTL): snapshot the current
            // left-gutter state and hide the built-in line numbers so they don't
            // duplicate the right-gutter renderer we are about to show.
            let shows_numbers = editor_view.shows_line_numbers();
            RTL_SAVED_LINE_NUMBERS.store(shows_numbers, Ordering::Relaxed);
            editor_view.set_show_line_numbers(false);
        }
        // Read the saved intent (either just stored above, or preserved from a
        // previous LTR→RTL transition and updated by apply_rtl_line_numbers).
        let shows = RTL_SAVED_LINE_NUMBERS.load(Ordering::Relaxed);

        // Create or reuse the right-gutter renderer.
        RTL_LINE_RENDERER.with(|cell| {
            let mut opt = cell.borrow_mut();
            if opt.is_none() {
                // First-ever RTL activation: create the right-gutter renderer.
                let renderer = GutterRendererText::new();
                renderer.set_xalign(1.0); // right-align digits toward outer edge of gutter
                renderer.set_yalign(0.5);
                renderer.set_xpad(12);
                // Populate each visible line with its 1-based number.
                renderer.connect_query_data(|r, _lines, line| {
                    r.set_text(&(line + 1).to_string());
                });
                let right_gutter =
                    sourceview5::prelude::ViewExt::gutter(editor_view, gtk4::TextWindowType::Right);
                right_gutter.insert(&renderer, 0);

                // ── Auto-size: deferred initial sizing (font may not be loaded yet) ──
                let renderer_sz = renderer.clone();
                let buf = gtk4::prelude::TextViewExt::buffer(editor_view);
                let buf_sz = buf.clone();
                // Track the last digit-count so connect_changed only calls
                // measure() when the count crosses a power-of-ten boundary.
                let last_digits = std::rc::Rc::new(std::cell::Cell::new(0usize));
                let last_digits_idle = last_digits.clone();
                gtk4::glib::idle_add_local_once(move || {
                    let count = buf_sz.line_count();
                    let mut n = count.max(1) as u32;
                    let mut d = 0usize;
                    while n > 0 {
                        n /= 10;
                        d += 1;
                    }
                    last_digits_idle.set(d);
                    set_renderer_size_for_line_count(&renderer_sz, count);
                });

                // ── Auto-size: resize when digit count changes ──
                // The signal stays connected permanently — the is_visible() guard
                // makes it a no-op while in LTR mode (essentially free), which is
                // simpler and more robust than disconnect+reconnect on every toggle
                // (reconnect was missing on re-entry, causing gutter sizing to break
                // permanently after the first LTR→RTL→LTR→RTL cycle).
                let renderer_sig = renderer.clone();
                buf.connect_changed(move |b| {
                    if renderer_sig.is_visible() {
                        let count = b.line_count().max(1) as u32;
                        let mut n = count;
                        let mut new_digits = 0usize;
                        while n > 0 {
                            n /= 10;
                            new_digits += 1;
                        }
                        if new_digits != last_digits.get() {
                            last_digits.set(new_digits);
                            set_renderer_size_for_line_count(&renderer_sig, b.line_count());
                        }
                    }
                });

                renderer.set_visible(shows);
                *opt = Some(renderer);
            } else if !previously_rtl {
                // Returning to RTL with an existing renderer (LTR→RTL after a
                // prior RTL session): restore visibility and re-sync gutter width
                // in case the line count crossed a digit boundary while in LTR.
                if let Some(r) = opt.as_ref() {
                    r.set_visible(shows);
                    // Re-sync size: the line count may have grown/shrunk across a
                    // digit boundary (9→10, 99→100, etc.) while the renderer was
                    // hidden and its is_visible() guard suppressed auto-resize.
                    let buf = gtk4::prelude::TextViewExt::buffer(editor_view);
                    set_renderer_size_for_line_count(r, buf.line_count());
                }
            }
            // already_rtl → renderer visibility is authoritative from the last
            // apply_rtl_line_numbers call; do not disturb it.
        });
    } else if previously_rtl {
        // RTL→LTR transition: hide the right-gutter renderer.
        RTL_LINE_RENDERER.with(|cell| {
            if let Some(r) = cell.borrow().as_ref() {
                r.set_visible(false);
            }
        });
        // NOTE: we intentionally do NOT disconnect the buffer-changed signal.
        // The signal handler's is_visible() guard makes it a no-op when the
        // renderer is hidden — essentially free — which avoids the complexity and
        // fragility of disconnecting here and reconnecting on every re-entry.
        // Restore the left-gutter line numbers to their pre-RTL state.
        let restore = RTL_SAVED_LINE_NUMBERS.load(Ordering::Relaxed);
        editor_view.set_show_line_numbers(restore);
        // already_ltr (else branch not entered): left-gutter line numbers are
        // managed by normal settings callbacks; do not touch them here.
    }

    // Pin the ScrolledWindow wrapping the source view to physical-right scrollbar
    // placement.  Calling sw.set_direction(RTL) here causes a *double-mirror* bug:
    // the parent container (Box/Paned) is already RTL-allocated, so the SW's own
    // RTL flip places the scrollbar at the SW's x=0 inside an RTL-allocated space
    // — pushing it off-screen to the far right or rendering it behind other widgets.
    // Child widgets inside the SW carry TextDirection::None and therefore inherit
    // RTL directly from set_default_direction(), so content still renders correctly.
    if let Some(parent) = editor_view.parent() {
        if let Ok(sw) = parent.downcast::<gtk4::ScrolledWindow>() {
            sw.set_direction(gtk4::TextDirection::Ltr);
        }
    }

    // Step 2 — update the application-wide default LAST.
    // All widgets still carrying TextDirection::None (toolbars, footer, menus,
    // popovers, TOC panel, etc.) will have direction-changed fired on them via
    // GTK's internal set_default_direction_recurse walk, which covers every
    // widget in every toplevel that hasn't been given an explicit direction.
    gtk4::Widget::set_default_direction(dir);

    log::debug!(
        "rtl: applied text direction → {}",
        if rtl { "RTL" } else { "LTR" }
    );
}

/// Applies a line-numbers show/hide request in a direction-aware way.
///
/// Called by the editor line-numbers callback (registered in `ui.rs`) so that
/// toggling line numbers works correctly regardless of the current direction:
///
/// * **LTR**: delegates directly to `editor_view.set_show_line_numbers`.
/// * **RTL**: shows/hides the right-gutter renderer instead of the left gutter.
///
/// Also keeps `RTL_SAVED_LINE_NUMBERS` up-to-date so that a subsequent LTR
/// toggle restores the correct state.
pub fn apply_rtl_line_numbers(show: bool, editor_view: &SourceView) {
    // Always record the current intent (survives RTL↔LTR round-trips).
    RTL_SAVED_LINE_NUMBERS.store(show, Ordering::Relaxed);

    if is_rtl_global() {
        // RTL active: drive the right-gutter renderer, not the left gutter.
        RTL_LINE_RENDERER.with(|cell| {
            if let Some(r) = cell.borrow().as_ref() {
                r.set_visible(show);
            }
        });
        // Left gutter numbers stay hidden regardless.
    } else {
        // LTR: normal path.
        editor_view.set_show_line_numbers(show);
    }
}
