name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GTK and WebKitGTK dependencies
      run: |
        sudo apt update
        sudo apt install \
          build-essential \
          pkg-config \
          libgtk-4-dev \
          libgtksourceview-5-dev \
          libwebkitgtk-6.0-dev \
          libsoup-3.0-dev

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --verbose
